### PR TITLE
Increase `Create[Private]MemoryBuffer` reliability 

### PR DESCRIPTION
**Pull request by marzent**
This is similar to https://github.com/Reloaded-Project/Reloaded.Memory.Buffers/pull/1, however also for `CreateMemoryBuffer`/`CreatePrivateMemoryBuffer`.
Initially I didn't notice it since it happens extremely rarely on x86, but it seems to be more common with wine running through Rosetta 2 on arm64 (with Dalamud).
There was also a tiny bug with https://github.com/Reloaded-Project/Reloaded.Memory.Buffers/pull/1 in that if `FindBufferLocation` threw an exception it would still throw "Failed to allocate memory using VirtualAlloc/VirtualAllocEx", which this also fixes.

### CODE REVIEW

**Comment by Sewer56** [comment]
LGTM

**Comment by Sewer56** [comment]
Could you re-test the current version of `Reloaded.Memory.Buffers` but with this hack removed?  

While I was testing for 4GB support on 32-bit Windows, I might have found the real cause of this issue; being the memory page cache. I removed for now as thinking back to it; such micro-optimisation that risks safety in what should be more of a mission critical library was overkill.

**Comment by marzent** [comment]
Sorry for the late reply, updating to the latest versions needed some changes on Dalamuds side.

Removing the workaround unfortunately still results in multiple failures like this:

```2022-06-28 13:07:40.026 +02:00 [ERR] [SVC] Service<ChatGui>: Construction failure
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Reloaded.Hooks.Tools.Utilities' threw an exception.
 ---> System.Exception: Failed to allocate memory using VirtualAlloc/VirtualAllocEx
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Run[T](Int32 retries, Func`1 function)
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Allocate(Int32 size, UIntPtr minimumAddress, UIntPtr maximumAddress, Int32 retryCount)
   at Reloaded.Assembler.Assembler.AllocateText(Int32 textSize, Int32 retryCount)
   at Reloaded.Assembler.Assembler..ctor(Int32 textSize, Int32 resultSize)
   at Reloaded.Hooks.Tools.Utilities..cctor()
   --- End of inner exception stack trace ---
   at Reloaded.Hooks.Tools.Utilities.CreateJump(UIntPtr targetPtr, Boolean is64Bit, Int32 minBytesUsed)
   at Reloaded.Hooks.X64.ReverseWrapper`1.Create(ReverseWrapper`1 reverseFunctionWrapper, UIntPtr functionPtr)
   at Reloaded.Hooks.X64.ReverseWrapper`1..ctor(TFunction function)
   at Reloaded.Hooks.Hook`1.CreateReverseWrapper(TFunction function)
   at Reloaded.Hooks.Hook`1..ctor(TFunction function, UIntPtr functionAddress, Int32 minHookLength, FunctionHookOptions options)
   at Reloaded.Hooks.ReloadedHooks.CreateHook[TFunction](TFunction function, Int64 functionAddress, Int32 minHookLength)
   at Reloaded.Hooks.ReloadedHooks.CreateHook[TFunction](TFunction function, Int64 functionAddress)
   at Dalamud.Hooking.Internal.ReloadedHook`1..ctor(IntPtr address, T detour, Assembly callingAssembly) in C:\goatsoft\companysecrets\dalamud\Hooking\Internal\ReloadedHook.cs:line 29
   at Dalamud.Hooking.Hook`1..ctor(IntPtr address, T detour, Boolean useMinHook, Assembly callingAssembly) in C:\goatsoft\companysecrets\dalamud\Hooking\Hook.cs:line 69
   at Dalamud.Hooking.Hook`1..ctor(IntPtr address, T detour) in C:\goatsoft\companysecrets\dalamud\Hooking\Hook.cs:line 35
   at Dalamud.Game.Gui.PartyFinder.PartyFinderGui..ctor(SigScanner sigScanner) in C:\goatsoft\companysecrets\dalamud\Game\Gui\PartyFinder\PartyFinderGui.cs:line 38
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Dalamud.Service`1.ConstructObject() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 180
   at Dalamud.Service`1.<>c.<<StartLoader>b__2_0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 53
```

Can try to get some wine traces as to what is happening with the virtual memory there later if that helps though.

**Comment by Sewer56** [comment]
If it still happens with workaround removed it's no big deal; I was personally curious since I thought the two might have been related.

**Pull request merged**
