### PR TITLE
Increase `MemoryBufferHelper.Allocate` reliability

### PR DESCRIPTION
**Pull request by marzent**
This change increases the minimum address for each failed allocation attempt, mitigating an issue where on wine `NtAllocateVirtualMemory` will return `STATUS_CONFLICTING_ADDRESSES` for the first few pages above the minimum address. 

The returned buffer will still satisfy size and proximity constraints and even iterating over the entire address range is virtually instantaneous.

### CODE REVIEW

**Comment by Sewer56** [comment]
Sorry for the delay; wasn't emotionally well lately, usually respond faster than this.

Can't personally verify or reproduce the issue myself, since it's been a while since I've worked on a *nix based environment (it's a bit difficult given the nature of my personal projects; also my keyboard has issues and sometimes I need multiple reboots to get it to work, ooof).

Tests pass, changes are minimal and code seems good. 
I'll just take your word for it that it helps.

**Comment by Sewer56** [comment]
Update: I propagated this dependency update across some different packages in the Reloaded spectrum such as `Reloaded.Hooks`, `Reloaded.Assembler` etc.

I'll probably propagate it to `Reloaded-II` (the mod loader) at some point aswell, however I haven't had reports from Wine users about this issue in a long while. I've mainly seen this issue reported in the context of people using Dalamud and FFXIV.

**Comment by marzent** [comment]
No worries, awesome it could be merged

**Comment by marzent** [comment]
> Update: I propagated this dependency update across some different packages in the Reloaded spectrum such as `Reloaded.Hooks`, `Reloaded.Assembler` etc.
> 
> I'll probably propagate it to `Reloaded-II` (the mod loader) at some point aswell, however I haven't had reports from Wine users about this issue in a long while. I've mainly seen this issue reported in the context of people using Dalamud and FFXIV.

Yeah this issue came up in the context of Dalamud, this is how failure would look like

```
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x21eb0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x21ec0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x21ed0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x21fd0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x21fe0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x220e0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x220f0000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x22143000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x2216e000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x2217e000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtQueryVirtualMemory (0xffffffffffffffff, 0x2218e000, info_class=0, 0x219180, 48, 0x219108)
0124:trace:virtual:NtAllocateVirtualMemory 0xffffffffffffffff 0x2218e000 00010000 2000 00000001
0124:fixme:virtual:NtAllocateVirtualMemory ret:2218E000  size:65536  zero:0 status:C0000018 type:8192
```

 And it would repeat multiple times, especially on setups either running through the Rosetta translation layer or on Linux with GShade also being in the virtual address space (which works fine on windows though)

**Comment by Sewer56** [comment]
This library got rewritten, with cross platform support and logic.
This will propagate soon onto Hooks.

I kept the brute force logic in that was specifically added for FFXIV, that said, can you verify it still works with the new library?

**Comment by marzent** [comment]
Yeah still works as expected, awesome to see the cross platform rewrite! 
Will it be possible to hook arm64 in the near future as well?

**Comment by Sewer56** [comment]
For `Reloaded.Hooks` ?

Not out of question. For [Reloaded3](https://reloaded-project.github.io/Reloaded-III/), (WIP Specification) I plan to see if I can get the core loader (and core mod dependencies) running fully cross platform.

This includes more exotic platforms, e.g. I'd like to experiment with Nintendo Switch (ARM64) at some point.

Achieving this however will need that some libraries (including this one) will need rewriting as native. Even if in .NET NativeAOT exists, every DLL built with it ships its own GC, which is unoptimal for game mods.
 Nevermind of course the fact that getting working build targets for homebrew there is extremely unlikely in the first place.

So I started with using Rust recently (currently porting this library). For Hooks, I plan to replace the current C# implementation with a Rust based one; and have the current C# library wrap it (should save ~100ms of JIT time on startup).

There are some technical limitations involved there. `Reloaded.Hooks` relies on FASM for hook generation, and that can only exist as DLL on Windows (due to the way relocations work, given FASM is written in assembly without position independent code). So I'll need to replace that with [iced](https://github.com/icedland/iced) entirely. This is possible for function hooks, but for `AsmHook`, well, it has overloads which accept FASM mnemonics...

Chances are I'll try to make an alternative to FASM for Reloaded.Hooks by making some stable API that wraps Iced's instruction encoder; and have that be the only option on the Rust side. Only catch-22 is, stable API there there will require some automatic code generation; X86 and extensions have 3500+ instructions (including overloads for different operands). But, must make sure a change in Iced wouldn't break existing use.

That said, on C# end, I need to maintain backcompat, so the C# wrapper will wind up retaining that functionality (by bringing it into wrapper) for Windows only. Ideally in long run, all future ASM hooks will use new encoder however. Complicated situation.

**Pull request merged**
